name: Publish to NPM
on:
  push:
    branches:
      - main
    paths: ["package.json"] # only trigger the action to publish a new build when package.json is modified; as the action only succeeds when the version name is updated anyways, this saves a lot of time

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn compile
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
